### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [shmillo/Plugin-Portfolio#2]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [DSPs](https://github.com/forart/HyMPS/blob/main/Guitar.md#dsps-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/shmillo/Plugin-Portfolio)
(generator URL: https://flat.badgen.net/github/license/shmillo/Plugin-Portfolio)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by shmillo** [comment]
Hello Forart,
Thanks for sharing my repository in your project! I have just added a GPL-2.0 license to it, and made sure that it appeared correctly in your Issue as well as in the DSP section.  Let me know if there are any further issues.
